spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    generate-ddl: 'true'
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: 'true'
        temp:
          use_jdbc_metadata_defaults: 'false'
        format_sql: 'false'
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://127.0.0.1:5432/test
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org:
      springframework:
        web: ERROR
        boot:
          autoconfigure: ERROR
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: ERROR
        SQL: ERROR
